"""
setup_env.py — Patch môi trường Kaggle sau khi đã cài dependencies.

Chỉ làm 3 việc (KHÔNG pip install — việc đó do cell 0-A lo):
  1. Uninstall torchvision/torchaudio bị broken
  2. Patch bitsandbytes để nhận CUDA 12.x của Kaggle
  3. Tạo stub torchvision để transformers không crash khi import

Có thể gọi theo 2 cách:
  - Import trực tiếp: from setup_env import setup_kaggle_env; setup_kaggle_env()
  - Chạy độc lập:    python setup_env.py
"""

from __future__ import annotations

import glob
import os
import subprocess
import sys


# ── helpers ───────────────────────────────────────────────────────────────────

def _run(cmd: str) -> None:
    """Chạy shell command, chỉ print khi có lỗi thật sự."""
    r = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    if r.returncode != 0 and r.stderr:
        # Lọc bỏ "not installed" warnings — không phải lỗi thật
        lines = [l for l in r.stderr.splitlines()
                 if 'error' in l.lower() and 'not installed' not in l.lower()]
        if lines:
            print('\n'.join(lines[-5:]))


def _patch_bitsandbytes() -> None:
    """Tạo symlink libbitsandbytes_cuda128.so nếu chưa có."""
    bnb_dir = '/usr/local/lib/python3.12/dist-packages/bitsandbytes'
    if not os.path.isdir(bnb_dir):
        return  # bitsandbytes chưa cài — bỏ qua

    so_128 = os.path.join(bnb_dir, 'libbitsandbytes_cuda128.so')
    if os.path.exists(so_128):
        return  # đã patch rồi

    so_files = sorted(glob.glob(os.path.join(bnb_dir, 'libbitsandbytes_cuda12*.so')))
    if so_files:
        best_so = so_files[-1]
        os.symlink(best_so, so_128)
        print(f"[setup_env] bitsandbytes patched: cuda128 → {os.path.basename(best_so)}")


def _stub_torchvision() -> None:
    """Tạo stub torchvision rỗng để transformers không crash khi import."""
    tv_dir = '/usr/local/lib/python3.12/dist-packages/torchvision'
    init_py = os.path.join(tv_dir, '__init__.py')
    if os.path.exists(init_py):
        return  # stub đã có

    os.makedirs(tv_dir, exist_ok=True)
    with open(init_py, 'w') as f:
        f.write('# stub — auto-generated by setup_env.py\n__version__ = "0.0.0"\n')
    print("[setup_env] torchvision stub created.")


def _remove_broken_av() -> None:
    """Gỡ torchvision/torchaudio bị broken (version mismatch với torch)."""
    _run('pip uninstall -y torchvision torchaudio 2>/dev/null || true')


# ── public API ────────────────────────────────────────────────────────────────

def setup_kaggle_env(verbose: bool = True) -> None:
    """
    Patch môi trường Kaggle. Gọi hàm này SAU KHI pip install đã xong.

    Args:
        verbose: In thông tin GPU/VRAM sau khi patch (default True).
    """
    _remove_broken_av()
    _patch_bitsandbytes()
    _stub_torchvision()

    if verbose:
        try:
            import torch
            print(f"[setup_env] Torch {torch.__version__} | CUDA {torch.version.cuda}")
            if torch.cuda.is_available():
                name = torch.cuda.get_device_name(0)
                vram = torch.cuda.get_device_properties(0).total_memory / 1e9
                print(f"[setup_env] GPU: {name}  ({vram:.1f} GB)")
                print("[setup_env] ✓ Môi trường Kaggle đã sẵn sàng. RESTART KERNEL rồi chạy tiếp.")
            else:
                print("[setup_env] ✗ Không tìm thấy GPU — vào Settings → Accelerator → T4.")
        except ImportError:
            print("[setup_env] torch chưa import được — restart kernel rồi kiểm tra lại.")


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    setup_kaggle_env()